apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-tracker
  namespace: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bug-tracker
  template:
    metadata:
      labels:
        app: bug-tracker
    spec:
      automountServiceAccountToken: false

      containers:
      - name: bug-tracker
        image: gsakshi0809/bug-tracker:__IMAGE_TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "500Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"

        volumeMounts:
        - name: temp-storage
          mountPath: /tmp

      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: "1Gi"
