apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-tracker
  namespace: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bug-tracker
  template:
    metadata:
      labels:
        app: bug-tracker
    spec:
      automountServiceAccountToken: false
      containers:
      - name: bug-tracker
        image: gsakshi0809/bug-tracking_system:1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
          - name: temp-storage
            mountPath: /tmp
      volumes:
        - name: temp-storage
          emptyDir:
            sizeLimit: "1Gi"
